[project]
name = "trimmer"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "freesimplegui>=5.2.0.post1",
    "imutils>=0.5.4",
    "numpy>=2.0.2",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.2",
    "pyyaml>=6.0.2",
]
